export type {
	CreatePlayerOptions,
	LavaSearchEntry,
	LavaSearchResult,
	LavaSearchResultType,
	LavaSearchTrack,
	ManagerErrorCode,
	ManagerEvents,
	ManagerOptions,
	MusicEvent,
	PartialQueueTrack,
	PlayerDataStore,
	PlayerErrorCode,
	PlayerSnapshot,
	PlayerTimestamps,
	QueueOptions,
	QueueTrack,
	SearchResultNormalized,
	TrackRequester,
} from "../structures/music/index.js";
export {
	defineMusicEvent,
	LavaSearchSource,
	LoopMode,
	ManagerError,
	MusicManager,
	MusicPlayer,
	MusicQueue,
	PlayerError,
	SearchSource,
} from "../structures/music/index.js";
